In [ ]:
#Pytorch is deep learning framework
# more tightly integrated with python than Tensor flow
# Supports dynamic computation graph (When build upa neural network, don't have to user same neural network for each epoc...
#can dynamically change neural networks on each epoc)
#uses gradient decent optimization and back propagation
# Like othe deep learning pytorch uses forward pass for prediction and backword pass for training and updating the wights
#of the model
# will understand autograd package in pytorch use for back propagation when train neural networks
# then use classes from pytorch to define neural network and connect them 
# building image classification model 
# convolutional neural network  in pytorch  and usi8ng pre trained model for image classification
# Text classification model using recurrent neural network

#after prediction of test outputs, it feed back the info to the classifier in order to improve model parameter .
# This is training phase. The feedback that trains machine learning model is called loss function and this is to 
#determine how far the prediction of model is from actual classification and this difference is used to improve your model. 

# Traditional ML bsed system: Expert to decide the features to pay attention Ex> Decission tree, Nive baised model, SVM
# Representation ML based models : figure out themselves what features in the input data are important. Ex: Neural networks

# Deep Learning: Classes of algorithms that learns which input data/feature are important or significant 
# Neural Network : Most common class of deep learning algorithm 
# Neural networks are built up of neurons 
# neurons are simple building block of the learning units within neural networks.
# neurons are mathmatical functions which takes input, perform computation using those inputs and produce output. 

#neural networks are composed of layers. inputs feed into the network passes through series of layers where each layer 
#performs some mathmatical operations of the input that apply. The output of one layer is fed to the input of another layer.
# visible layers: those layers which take the input and produce the output. In between visible layers there can be 
#n number of layers(hidden layers of neural network).

# every layer in neural network is made up of a number of active learning units, individual interconnected neurons.
#The output of neurons in one layer are the inputs to the neuron of next layer. So nerons of every layer is connected
#behind it and ahead of it. 

#neurons are single mathmatical functions which takes no of inputs and process it and produces no of outputs.
# These outputs can be passed on to multiple neurons on next lavel 
# the output of one neuron is associated with a weight when connects to another neuron 
#(W value depends upon how strong the neuron is sensitive to the output of another neuron)
#The connections between neurons called as tensors
# Within every single Neurons two functions are there : Affine Transformation: Activation function
# Affine Transformation: It is represents the linear relationships between inputs and output in the neuron.
# Activation Function: output from Affine Transformation is fed to Activation function 
# Combination of Affine Transformaton and Activation Function learns any arbitary relationship between input and output

# Pytorch uses a "Tape-Based-Autograd" system using and replaying a tape recorder to adjust the weight of model 

#https://pytorch.org/get-started/locally/

In [5]:
# tensors are cetral data normally represented by 3 characterstics.
# Rank : No of Dimensions
# shape : No of elements in each dimension
# Type : data type may ne int, float, boolean etc

In [8]:
import torch 
print(torch.__version__)

1.0.1


In [10]:
tensor_array= torch.Tensor([[1,2],[4,5]])  #2D tensor
tensor_array

tensor([[1., 2.],
        [4., 5.]])

In [11]:
tensor_uninitialized= torch.Tensor(3,3)    # created 2D array
torch.numel(tensor_uninitialized)          # numel returns no of elements in a tensor

9

In [12]:
tensor_uninitialized

tensor([[ 0.0000e+00,  0.0000e+00,  3.9852e-21],
        [ 5.1848e-44, -4.0968e+15,  8.3097e-43],
        [ 1.1070e-43,  0.0000e+00,  0.0000e+00]])

In [14]:
tensor_intialized=torch.rand(3,3)      # randomly initialized
tensor_intialized

tensor([[0.8349, 0.4843, 0.1481],
        [0.5463, 0.7692, 0.3081],
        [0.1237, 0.7667, 0.9988]])

In [15]:
tensor_int=torch.randn(5,3).type(torch.IntTensor)     # type= integer
tensor_int

tensor([[-1,  0,  1],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [-1,  0,  0]], dtype=torch.int32)

In [16]:
tensor_long=torch.LongTensor([5.0,3.2,2.0])     # float value
tensor_long

tensor([5, 3, 2])

In [17]:
tensor_byte=torch.ByteTensor([0,261,1,-5])     # value range is 0 to 255. any value not in range will express relative to 255
tensor_byte

tensor([  0,   5,   1, 251], dtype=torch.uint8)

In [19]:
tensor_one=torch.ones(10)     # print 1 values 
tensor_one

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
tensor_zero=torch.zeros(10)     # print zeros
tensor_zero

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
tensor_eye=torch.eye(3)     # .eye will give a square matrix with all diagonal as value 1
tensor_eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [24]:
tensor_nonzero=torch.nonzero(tensor_eye)     # .nonzero will give positions of non zero elements
tensor_nonzero

tensor([[0, 0],
        [1, 1],
        [2, 2]])

In [25]:
tensor_ones_shape_eye=torch.ones_like(tensor_eye)     # .ones_like will give one value of same shape
tensor_ones_shape_eye

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [26]:
# tensors performs two kind of operations
# In place operation : this operation modify the existing tensor 
# Out of place operation : This generates a new tensor

initial_tensor= torch.rand(3,3)      # generates a new tensor and fill value 3 for all position (in place operation)
initial_tensor.fill_(3)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [27]:
new_tensor = initial_tensor.add(4)    # out of place operation so suffix"_" is not used here
new_tensor

tensor([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]])

In [28]:
initial_tensor.add_(5)      #in place operation 
initial_tensor

tensor([[8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.]])

In [32]:
import numpy as np
numpy_arr= np.array([1,2,3])       # array using numpy
numpy_arr

array([1, 2, 3])

In [33]:
tensor= torch.from_numpy(numpy_arr)   # fetching the same from numpy display same result as a tensor
tensor

tensor([1, 2, 3], dtype=torch.int32)

In [34]:
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([1, 2, 3])

In [35]:
numpy_arr[1]=4      #update the array index
numpy_arr

array([1, 4, 3])

In [36]:
tensor         # tensor is also getting updated automatically once array updated
                #

tensor([1, 4, 3], dtype=torch.int32)

In [37]:
%pwd


'C:\\Users\\suvanje13799'